baseurl:

# Site settings
email: Arneva47@gmail.com
description: "Mikroautobusų oro pakabos. Suminkština jūsų važiuoklę ir padeda mikroautobusui išlaikyti didesnį svorį kelyje nenusodinant važiuoklės."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: 333 
  secondary-dark: 000




# Postal address (add as many lines as necessary)
address:
  - line: Lokių
  - line: Vilkaviškis, LT 2012

# Build settings
markdown: kramdown
permalink: pretty
